{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "2f047ead_6288c4fa",
        "filename": "include/sdbusplus/async/fdio.hpp",
        "patchSetId": 2
      },
      "lineNbr": 97,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2025-09-24T20:11:07Z",
      "side": 1,
      "message": "Should we terminate if timedOut\u003d\u003dtrue here?",
      "revId": "3fbd4b9ef799ef5d9d45514be3f7e2b441a4679c",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "b498c9f2_46fbec20",
        "filename": "include/sdbusplus/async/fdio.hpp",
        "patchSetId": 2
      },
      "lineNbr": 102,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2025-09-24T20:11:07Z",
      "side": 1,
      "message": "Why did we add this if it does nothing?  That seems like we could potentially end up dropping a missed error?   Go ahead and call `set_error` here so we don\u0027t miss this in the future.",
      "revId": "3fbd4b9ef799ef5d9d45514be3f7e2b441a4679c",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "483a926a_8abc9dee",
        "filename": "include/sdbusplus/async/fdio.hpp",
        "patchSetId": 2
      },
      "lineNbr": 153,
      "author": {
        "id": 1000000
      },
      "writtenOn": "2025-09-24T20:11:07Z",
      "side": 1,
      "message": "I don\u0027t really like that we have a timeout as a bool but we also now have a `set_error` for certain exceptions.  Can we treat a timeout as an exception and `set_error` in that case also?",
      "range": {
        "startLine": 149,
        "startChar": 0,
        "endLine": 153,
        "endChar": 9
      },
      "revId": "3fbd4b9ef799ef5d9d45514be3f7e2b441a4679c",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ]
}